version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stripe_web
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: stripe_redis
    ports:
      - "6379:6379"
